#!/usr/bin/env python

import os
import os.path
import sys
import subprocess
import time

def main():
      srcdir = os.environ['SRCDIR']
      datadir = os.environ['DATADIR']
      stubdir = os.path.join(srcdir, '..')
      smtpddir = os.path.join(datadir, 'smtpddir')

      os.chdir(datadir)

      os.mkdir(smtpddir)

      env = os.environ.copy()
      env['STUB_SMTPD_DATADIR'] = smtpddir

      smtpd = subprocess.Popen([os.path.join(stubdir, 'smtpd'), '--port=4321'],
                               env=env)

      time.sleep(1)

      subprocess.call([os.path.join(stubdir, 'smtpclient'), '--port=4321'])

      time.sleep(1)

      smtpd.kill()

      # print all the files to make sure there are no extra mails
      print 'files: %s' % os.listdir(smtpddir)

      # cat smtpddir/0
      mail0 = os.path.join(smtpddir, '0')
      f = open(mail0, 'r')
      print f.read()

      # cleanup
      os.remove(mail0)
      os.rmdir(smtpddir)

if __name__ == "__main__":
      main()
