#!/usr/bin/env python

import os
import os.path
import sys
import subprocess
import time

def main():
      smtpddir = 'smtpddir'
      srcdir = os.environ['SRCDIR']
      datadir = os.environ['DATADIR']
      stubdir = os.path.join(srcdir, '..')

      os.chdir(datadir)

      os.mkdir(smtpddir)

      smtpd = subprocess.Popen([os.path.join(stubdir, 'smtpd'), '--port=4321'])

      time.sleep(1)

      subprocess.call([os.path.join(stubdir, 'smtpclient'), '--port=4321'])

      time.sleep(1)

      smtpd.kill()

      # print all the files to make sure there are no extra mails
      print 'files: %s' % os.listdir(smtpddir)

      # cat smtpddir/0
      f = open(os.path.join(smtpddir, '0'), 'r')
      print f.read()

if __name__ == "__main__":
      main()
