name: tests-all
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install pycodestyle pyflakes3 cmdtest figlet python3-flask-restful python3-pexpect python3-aiosmtpd python3-mock diffstat
      - run: ./run_tests
